### ISSUE TITLE
Recommended way of running the code

### ISSUE THREAD

**Issue by mdouze** [stanford-futuredata/simdex#1]
Hi 
I am working on maximum inner product search. I managed to compile the executable in the `cpp` subdirectory. However I am not sure this implements the "To index or not to index" paper. 

What is the proper way of using optimus-maximus?

Running `simdex` with on a test dataset in CSV format (10k queries, 100k probes, 128 dimensions) gives: 
```
 ./simdex --weights-dir /data/users/matthijs/MIPS_data/ -k 10 --base-name /data/users/matthijs/MIPS_data/run1 --num-clusters 100 --num-items 100000 --num-users 10000 --num-latent-factors 128
Loading /data/users/matthijs/MIPS_data//item_weights.csv....
Loading /data/users/matthijs/MIPS_data//user_weights.csv....
Starting now
parse time: 5.131497 secs
cluster time: 0.149917 secs
index time: 0.174558 secs
algo time: 98.537758 secs
total comp time: 98.862233 secs
```
The only mandatory argument is the number of clusters. Are there other parameters that are worthwhile to tune? It seems that within the range 100-1000 that parameter does not have a large impact on speed. 

Also, it would be interesting to have the CSV files corresponding to the datasets used in the paper (table 1). Would it be possible to share those? 

Thanks!

**Comment by fabuzaid21** [comment]
Hi @mdouze, thanks for the questions. You can also try tuning the batch size (`--batch-size`), which controls how many items are batched during index traversal at query time. We typically used `--batch-size=4096` in our experiments, and it definitely has an impact on runtime.

For the number of clusters, it may be helpful to use a smaller number of clusters (e.g., 8, 16, or 32) if the number of users is small (e.g., 10K). We used a larger number of clusters (e.g., 256 or 512), on models that had 500K users or more.

There are other parameters that can be tuned, but the default values should be fine; not much tuning is required. If you want to see a full example of all the parameters that can be tuned, check out https://github.com/stanford-futuredata/optimus-maximus/blob/master/benchmark/simdex.sh. 

I'm working on uploading the CSV model files that we benchmarked on to a public S3 bucket; I'll share the links once they're done. Let me know if you have any more questions!
